kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: file-integrity-operator
  namespace: openshift-file-integrity
subjects:
- kind: ServiceAccount
  name: file-integrity-operator
roleRef:
  kind: Role
  name: file-integrity-operator
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: scc-priv
  namespace: openshift-file-integrity
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: scc-priv
subjects:
  - kind: ServiceAccount
    name: file-integrity-operator