apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    description: An operator that manages file integrity checks on nodes.
    categories: Security
    certified: 'False'
    containerImage: 'quay.io/file-integrity-operator/file-integrity-operator:0.1.0'
    createdAt: 2012-01-01 00:00:00
    repository: 'https://github.com/openshift/file-integrity-operator'
    support: Red Hat
    alm-examples: |-
      [
        {
          "apiVersion": "file-integrity.openshift.io/v1alpha1",
          "kind": "FileIntegrity",
          "metadata": {
            "name": "example-fileintegrity",
            "namespace": "openshift-file-integrity"
          },
          "spec": {
            "config": {}
          }
        }
      ]
    capabilities: Basic Install
  name: file-integrity-operator.v0.1.0
  namespace: openshift-file-integrity
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - name: fileintegrities.file-integrity.openshift.io
      version: v1alpha1
      kind: FileIntegrity
      displayName: FileIntegrity
      description: An instance of file integrity checks
  description: An operator that manages file integrity checks on nodes.
  displayName: File Integrity Operator
  install:
    spec:
      deployments:
      - name: file-integrity-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: file-integrity-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: file-integrity-operator
            spec:
              containers:
              - command:
                - file-integrity-operator
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: file-integrity-operator
                image: quay.io/file-integrity-operator/file-integrity-operator:0.1.0
                imagePullPolicy: Always
                name: file-integrity-operator
                resources: {}
              nodeSelector:
                node-role.kubernetes.io/master: ""
              serviceAccountName: file-integrity-operator
              tolerations:
              - effect: NoSchedule
                key: node-role.kubernetes.io/master
                operator: Exists
              - effect: NoExecute
                key: node.kubernetes.io/unreachable
                operator: Exists
                tolerationSeconds: 120
              - effect: NoExecute
                key: node.kubernetes.io/not-ready
                operator: Exists
                tolerationSeconds: 120
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - services/finalizers
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - file-integrity-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - get
        - apiGroups:
          - apps
          resources:
          - replicasets
          verbs:
          - get
        - apiGroups:
          - file-integrity.openshift.io
          resources:
          - '*'
          verbs:
          - '*'
        serviceAccountName: file-integrity-operator
      - rules:
        - apiGroups:
          - security.openshift.io
          resourceNames:
          - privileged
          resources:
          - securitycontextconstraints
          verbs:
          - use
        serviceAccountName: file-integrity-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: false
    type: AllNamespaces
  maturity: alpha
  keywords:
    - Integrity
  links:
    - name: Documentation
      url: https://github.com/openshift/file-integrity-operator/README.md
  provider:
    name: Red Hat
  maintainers:
    - email: mrogers@redhat.com
      name: Matt Rogers
  version: 0.1.0
